export const brands = [
  { name: "Apple", models: ["MacBook Air", "MacBook Pro", "Others"] },
  {
    name: "Dell",
    models: ["XPS", "Inspiron", "Latitude", "Alienware", "G Series", "Others"],
  },
  {
    name: "HP",
    models: ["Spectre", "Envy", "Pavilion", "Omen", "ProBook", "Others"],
  },
  {
    name: "Lenovo",
    models: ["ThinkPad", "IdeaPad", "Yoga", "Legion", "Others"],
  },
  {
    name: "Asus",
    models: ["ZenBook", "VivoBook", "ROG", "TUF Gaming", "Others"],
  },
  { name: "Acer", models: ["Aspire", "Nitro", "Spin", "Others"] },
  {
    name: "MSI",
    models: [
      "Alpha Series",
      "Bravo Series",
      "Delta Series",
      "Raider GE Series",
      "Stealth GS Series",
      "Other",
    ],
  },
  // Add more brands and their models as needed
];

export const operatingSystem = [
  "Chrome OS",
  "DOS",
  "Linux",
  "MAC",
  "Ubuntu",
  "Windows",
  "Others",
];

export const area = [
  {
    region: "Punjab",
    city: [
      "Lahore",
      "Faisalabad",
      "Rawalpindi",
      "Gujranwala",
      "Multan",
      "Bahawalpur",
      "Sargodha",
      "Sialkot",
      "Sheikhupura",
      "Rahim Yar Khan",
      "Jhang",
      "Dera Ghazi Khan",
      "Gujrat",
      "Sahiwal",
      "Wah Cantonment",
      "Kasur",
      "Okara",
      "Chiniot",
      "Kamoke",
      "Hafizabad",
      "Sadiqabad",
      "Burewala",
      "Khanewal",
      "Muzaffargarh",
      "Mandi Bahauddin",
      "Jhelum",
      "Khanpur",
      "Pakpattan",
      "Daska",
      "Gojra",
      "Muridke",
      "Bahawalnagar",
      "Samundri",
      "Jaranwala",
      "Chishtian",
      "Attock",
      "Vehari",
      "Kot Abdul Malik",
      "Ferozewala",
      "Chakwal",
      "Gujranwala Cantonment",
      "Kamalia",
      "Ahmedpur East",
      "Kot Addu",
      "Wazirabad",
      "Layyah",
      "Taxila",
      "Khushab",
      "Mianwali",
      "Lodhran",
      "Hasilpur",
      "Bhakkar",
      "Arif Wala",
      "Sambrial",
      "Jatoi",
      "Haroonabad",
      "Narowal",
      "Bhalwal",
    ],
  },
  {
    region: "Balochistan",
    city: [
      "Quetta",
      "Turbat",
      "Khuzdar",
      "Hub, Balochistan",
      "Chaman",
      "Gwadar",
      "Dera Murad Jamali",
      "Dera Allah Yar",
      "Usta Mohammad",
      "Sui Town",
      "Sibi",
      "Loralai",
      "Tump",
      "Nushki",
      "Zhob",
      "Kharan",
      "Chitkan",
      "Khanozai",
      "Buleda",
      "Saranan",
      "Zehri",
      "Qalat",
      "Tasp",
      "Surab",
      "Pishin",
      "Mastung",
      "Qilla Saifullah",
      "Pasni",
      "Nal",
      "Winder",
      "Uthal",
      "Huramzai",
      "Muslim Bagh",
      "Dera Bugti",
      "Qilla Abdullah",
      "Bela",
      "Wadh",
      "Washuk",
      "Awaran",
      "Machh",
      "Jiwani",
      "Ormara",
      "Kohlu",
      "Bhag",
      "Dalbandin",
      "Dhadar",
      "Musakhel",
      "Harnai",
      "Dureji",
      "Sohbatpur",
      "Gajjar Mashkay",
      "Barkhan",
      "Shahrug",
      "Duki",
    ],
  },
  {
    region: "Khyber Pakhtunkhwa",
    city: [
      "Peshawar",
      "Mardan",
      "Mingora",
      "Kohat",
      "Dera Ismail Khan",
      "Abbottabad",
      "Mansehra",
      "Swabi",
      "Nowshera",
      "Kabal",
      "Charsadda",
      "Barikot",
      "Shabqadar",
      "Haripur",
      "Takht-i-Bahi",
      "Paharpur",
      "Batkhela",
      "Jamrud",
      "Bahrain",
      "Lakki Marwat",
      "Pabbi",
      "Topi",
      "Jehangira",
      "Karak",
      "Bannu",
      "Chitral",
      "Hangu",
      "Havelian",
      "Khwazakhela",
      "Khalabat",
      "Tank",
      "Dir",
      "Matta",
      "Tordher",
      "Timargara",
      "Paroa",
      "Amangarh",
      "Risalpur",
      "Nawan Shehr",
      "Sadda",
      "Landi Kotal",
      "Tangi",
      "Akora Khattak",
      "Tall",
      "Zaida",
      "Utmanzai",
    ],
  },
  {
    region: "Sindh",
    city: [
      "Latifabad",
      "Karachi",
      "Bhiria City",
      "Bhiria Road",
      "Bhirkan",
      "Boriri",
      "Chak",
      "Dadu",
      "Daharki",
      "Daulatpur",
      "Digri",
      "Diplo",
      "Dokri",
      "Gambat",
      "Garhi Yasin",
      "Ghotki",
      "Guddu Barrage",
      "Hala",
      "Khairpur Mirs",
      "Hyderabad",
      "Isl...nasirabad",
      "Naudero",
      "Naushahro Feroze",
      "Nawabshah",
      "New Saeedabad",
      "Pir Jo Goth",
      "Piryaloi",
      "Qambar",
      "Qasimabad",
      "Qubo Saeed Khan",
      "Rajo Khanani",
      "Ranipur",
      "Ratodero",
      "Rohri",
      "Sakrand",
      "Samaro",
      "Sanghar",
      "Sann",
      "Sehwan Sharif",
    ],
  },
];
